// <auto-generated />
namespace MyBudgetCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addshortdesctomonthlybudgettable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addshortdesctomonthlybudgettable));
        
        string IMigrationMetadata.Id
        {
            get { return "202103221623080_add short descto monthly budget table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
