// <auto-generated />
namespace MyBudget.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateparentidtonullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateparentidtonullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202102120852052_update parent id to nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
